spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibertate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: postgres
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: fast_campus.sns-application-2023.secret_key
  #30 Days
  token.expired-time-ms: 2592000000
